name: yandex_eats_clone
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animations: ^2.0.11
  api:
    path: api
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  env:
    path: packages/env
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^3.3.0
  flexible_wrap: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_credit_card: ^4.0.1
  flutter_stripe: ^11.0.0
  form_fields:
    path: packages/form_fields
  geocode: ^1.0.3
  go_router: ^14.2.7
  google_maps_flutter: ^2.9.0
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  location_repository:
    path: packages/location_repository
  orders_repository:
    path: packages/orders_repository
  path_provider: ^2.1.3
  payments_repository:
    path: packages/payments_repository
  persistent_storage:
    path: packages/storage/persistent_storage
  resturants_repository:
    path: packages/resturants_repository
  shared:
    path: packages/shared
  shared_preferences: ^2.3.2
  stripe_payments_client:
    path: packages/payment_client/stripe_payments_client
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.3.0
  user_repository:
    path: packages/user_repository
  web_socket_client: ^0.1.4

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

  very_good_analysis: ^6.0.0
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
