name: location_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
dependencies:
  api:
    path: ../../api
  dio: ^5.6.0
  env:
    path: ../env
  equatable: ^2.0.5
  geolocator: ^12.0.0
  json_annotation: ^4.9.0
